name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Jab aap main branch par push karenge tab ye chalega

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Authorize Docker
      run: gcloud auth configure-docker

    - name: Build and Push Docker Image
      run: |-
        # Naya path: region-docker.pkg.dev/project-id/repo-name/image-name
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-repo/flask-app:${{ github.sha }} .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-repo/flask-app:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy flask-app \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-repo/flask-app:${{ github.sha }} \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated